language: go

go:
- 1.13.x

os:
  - linux

addons:
  apt:s
    packages:
    - snapd

git:
  depth: 1

env:
  global:
  - PATH=/snap/bin:$PATH
  - GO111MODULE=on

before_script:
- go get -t -v ./...
- go get -u github.com/gobuffalo/packr/v2/packr2

script:
- packr2
- go build

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"

after_success:
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

notifications:
  email: false